Allow upstream bundles to be built
clearlinux/clr-distro-factory pull request #45
Opened 2019-10-29 20:27 UTC by gtkramer

When an upstream builds a mix, they will source all bundle definitions
locally.  Because upstream logic is largely different from downstream
logic when using mixer, introduce a flag that toggles the commands that
get run if one is an upstram vs a downstream.  If this flag is not
defined, the condition evaluates to false and the downstream logic is
maintained by default.

Also introduce a MIXER_OPTS variable so that upstream may be able to
define in its config that it also wants the offline option, but default
to the native option to preserve existing deployment logic.

Signed-off-by: George T Kramer <george.t.kramer@intel.com>

2019-10-30 16:08 UTC, mbelluzzo commented on release/mixer.sh
> +MIXER_OPTS=${MIXER_OPTS:-"--native"}
You should had that change on its own commit instead of part of every PR :-P

2019-10-30 19:50 UTC, gtkramer commented on release/mixer.sh
> +MIXER_OPTS=${MIXER_OPTS:-"--native"}
XD

2019-10-30 20:10 UTC, gtkramer commented on release/mixer.sh
> +MIXER_OPTS=${MIXER_OPTS:-"--native"}
separate PR opened to handle this all in one go #51

2019-10-31 02:10 UTC, mbelluzzo commented
After merging your other PRs, this one got outdated so it needs rebase. But I would take the rebase opportunity to approach this change a little bit differently.

Think an upstream as a downstream that does not points to Clear Linux (and that would work for Clear itself). So consider that the bundles that always needs building is the ones on DS_BUNDLES (which is the default behavior today). So this change can be just:

```bash
if ! "${IS_UPSTREAM}"; then
    mixer bundle add ${CLR_BUNDLES} ... #original code here
fi
```

Image that Clear may not be the only one wanting to use distro-factory to be an upstream. It may be that one does not want to add all bundles definition just because it is an upstream. The original code already handles that. It allows the "upstream" to set DS_BUNDLES to a subset of the bundles in 'local-bundles' to mix.

Maybe moving forward. It is time to change the name of this var back to MIX_BUNDLES (it was its original name :-/)

2019-10-31 02:10 UTC, mbelluzzo requested changes
see previous comment

2019-10-31 18:13 UTC, gtkramer commented
Ah, yes, that makes sense.  Since an upstream will always be working with local bundles, we should only put a condition around the one bundle add rather than both.  The naming of the variables CLR_BUNDLES and DS_BUNDLES threw me off because I figured the upstream is who owns the CLR_BUNDLES.  I'll rebase and make the change.

2019-11-04 20:11 UTC, gtkramer commented
@mbelluzzo @vinaypotluri how does this look?

2019-11-06 20:45 UTC, mbelluzzo commented
Merged with re-worked commit message as agreed IRL

2019-11-06 20:45 UTC, closed without merging